# Generated by Django 5.0.4 on 2024-04-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choices_text',
            new_name='choice_text',
        ),
    ]
